export default {
  DX_SCROLL: 'DX_SCROLL',
  DX_FEED_BACK: 'DX_FEED_BACK',
  DX_FEED_BACK_COMPLETE: 'DX_FEED_BACK_COMPLETE',
  DX_BROWSER: 'DX_BROWSER',
  DX_BROWSER_BACK: 'DX_BROWSER_BACK',
  DX_SECTION_BROWSER: 'DX_SECTION_BROWSER',
  DX_SECTION_BROWSER_BACK: 'DX_SECTION_BROWSER_BACK',
  DX_SECTION_SUGGEST_BROWSER: 'DX_SECTION_SUGGEST_BROWSER',
  DX_ADD_BOOKMARK: 'DX_ADD_BOOKMARK',
  DX_ADD_FEED_TO_DOWNLOAD: 'DX_ADD_FEED_TO_DOWNLOAD',
  DX_DELETE_BOOKMARK: 'DX_DELETE_BOOKMARK',
  DX_DELETE_DOWNLOAD: 'DX_DELETE_DOWNLOAD',

  // Read local directory
  DX_GET_DOWNLOADS_DIRECTORY_REQUEST: 'DX_GET_DOWNLOADS_DIRECTORY_REQUEST',
  DX_GET_DOWNLOADS_DIRECTORY_SUCCESS: 'DX_GET_DOWNLOADS_DIRECTORY_SUCCESS',
  DX_GET_DOWNLOADS_DIRECTORY_ERRORS: 'DX_GET_DOWNLOADS_DIRECTORY_ERRORS',

  // Add feed to download
  DX_ADD_FEED_TO_DOWNLOAD_REQUEST: 'DX_ADD_FEED_TO_DOWNLOAD_REQUEST',
  DX_ADD_FEED_TO_DOWNLOAD_SUCCESS: 'DX_ADD_FEED_TO_DOWNLOAD_SUCCESS',
  DX_ADD_FEED_TO_DOWNLOAD_ERRORS: 'DX_ADD_FEED_TO_DOWNLOAD_ERRORS',

  // Delete feed from download
  DX_DELETE_FEED_FROM_DOWNLOAD_REQUEST: 'DX_DELETE_FEED_FROM_DOWNLOAD_REQUEST',
  DX_DELETE_FEED_FROM_DOWNLOAD_SUCCESS: 'DX_DELETE_FEED_FROM_DOWNLOAD_SUCCESS',
  DX_DELETE_FEED_FROM_DOWNLOAD_ERRORS: 'DX_DELETE_FEED_FROM_DOWNLOAD_ERRORS',

  // Get Featured Cards
  DX_GET_FEATURED_CARDS_REQUEST: 'DX_GET_FEATURED_CARDS_REQUEST',
  DX_GET_FEATURED_CARDS_SUCCESS: 'DX_GET_FEATURED_CARDS_SUCCESS',
  DX_GET_FEATURED_CARDS_ERRORS: 'DX_GET_FEATURED_CARDS_ERRORS',

  // Get Featured Cards
  DX_GET_MOST_POPULAR_CARDS_REQUEST: 'DX_GET_MOST_POPULAR_CARDS_REQUEST',
  DX_GET_MOST_POPULAR_CARDS_SUCCESS: 'DX_GET_MOST_POPULAR_CARDS_SUCCESS',
  DX_GET_MOST_POPULAR_CARDS_ERRORS: 'DX_GET_MOST_POPULAR_CARDS_ERRORS',

  // Get Featured Cards
  DX_GET_NEW_RELEASES_CARDS_REQUEST: 'DX_GET_NEW_RELEASES_CARDS_REQUEST',
  DX_GET_NEW_RELEASES_CARDS_SUCCESS: 'DX_GET_NEW_RELEASES_CARDS_SUCCESS',
  DX_GET_NEW_RELEASES_CARDS_ERRORS: 'DX_GET_NEW_RELEASES_CARDS_ERRORS',

  // Get Featured Cards
  DX_GET_TRENDING_CARDS_REQUEST: 'DX_GET_TRENDING_CARDS_REQUEST',
  DX_GET_TRENDING_CARDS_SUCCESS: 'DX_GET_TRENDING_CARDS_SUCCESS',
  DX_GET_TRENDING_CARDS_ERRORS: 'DX_GET_TRENDING_CARDS_ERRORS',

};
