export default {
  DX_POST_CHANNEL_LIST_REQUEST: 'DX_POST_CHANNEL_LIST_REQUEST',
  DX_POST_CHANNEL_LIST_SUCCESS: 'DX_POST_CHANNEL_LIST_SUCCESS',
  DX_CHANNELS_ERRORS: 'DX_CHANNELS_ERRORS',

  DX_POST_CHANNEL_SUBSCRIBE_REQUEST: 'DX_POST_CHANNEL_SUBSCRIBE_REQUEST',
  DX_POST_CHANNEL_SUBSCRIBE_SUCCESS: 'DX_POST_CHANNEL_SUBSCRIBE_SUCCESS',
  DX_POST_CHANNEL_SUBSCRIBE_FAILURE: 'DX_POST_CHANNEL_SUBSCRIBE_FAILURE',
};
