export default {

  DX_SCROLL_W: 'DX_SCROLL_W',
  DX_FEED_BACK_W: 'DX_FEED_BACK_W',
  DX_FEED_BACK_COMPLETE_W: 'DX_FEED_BACK_COMPLETE_W',
  DX_BROWSER_W: 'DX_BROWSER_W',
  DX_BROWSER_BACK_W: 'DX_BROWSER_BACK_W',
  DX_SECTION_BROWSER_W: 'DX_SECTION_BROWSER_W',
  DX_SECTION_BROWSER_BACK_W: 'DX_SECTION_BROWSER_BACK_W',
  DX_SECTION_SUGGEST_BROWSER_W: 'DX_SECTION_SUGGEST_BROWSER_W',

};
