export default {
  DX_SCROLL: 'DX_SCROLL',
  DX_FEED_BACK: 'DX_FEED_BACK',
  DX_FEED_BACK_COMPLETE: 'DX_FEED_BACK_COMPLETE',
  DX_BROWSER: 'DX_BROWSER',
  DX_BROWSER_BACK: 'DX_BROWSER_BACK',
  DX_SECTION_BROWSER: 'DX_SECTION_BROWSER',
  DX_SECTION_BROWSER_BACK: 'DX_SECTION_BROWSER_BACK',
  DX_SECTION_SUGGEST_BROWSER: 'DX_SECTION_SUGGEST_BROWSER',
  DX_ADD_BOOKMARK: 'DX_ADD_BOOKMARK',
  DX_BROWSE_TO_SECTION_PAGE: 'DX_BROWSE_TO_SECTION_PAGE',
  DX_BROWSE_TO_CHANNEL_PAGE: 'DX_BROWSE_TO_CHANNEL_PAGE',

  DX_DELETE_BOOKMARK: 'DX_DELETE_BOOKMARK',
  DX_DELETE_DOWNLOAD: 'DX_DELETE_DOWNLOAD',

  DX_POST_STREAM_EXPRERIENCE_LIST_REQUEST: 'DX_POST_STREAM_EXPRERIENCE_LIST_REQUEST',
  DX_POST_STREAM_EXPRERIENCE_LIST_SUCCESS: 'DX_POST_STREAM_EXPRERIENCE_LIST_SUCCESS',
  DX_POST_STREAM_EXPRERIENCE_LIST_ERRORS: 'DX_POST_STREAM_EXPRERIENCE_LIST_ERRORS',

  DX_POST_STREAM_EXPRERIENCE_CARD_INFO_REQUEST: 'DX_POST_STREAM_EXPRERIENCE_CARD_INFO_REQUEST',
  DX_POST_STREAM_EXPRERIENCE_CARD_INFO_SUCCESS: 'DX_POST_STREAM_EXPRERIENCE_CARD_INFO_SUCCESS',
  DX_POST_STREAM_EXPRERIENCE_CARD_INFO_ERRORS: 'DX_POST_STREAM_EXPRERIENCE_CARD_INFO_ERRORS',

  POST_FEEDBACK: 'POST_FEEDBACK',
};
